run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gofmt
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  gosec:
    excludes:
      - G104

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
