version: "2"

run:
  go: "1.23"
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    gosec:
      excludes:
        - G104

formatters:
  enable:
    - gofmt
